language: bash

services:
- docker

env:
  matrix:
  - ALPINE_VER=3.11.3 TAGS=3.11,3,latest
  - ALPINE_VER=3.10.4 TAGS=3.10
  - ALPINE_VER=3.9.5 TAGS=3.9
  - ALPINE_VER=3.8.5 TAGS=3.8
  - ALPINE_VER=3.11.3 TAGS=3.11-dev,3-dev,dev ALPINE_DEV=1

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
