language: bash

sudo: required

services:
  - docker

env:
  global:
#    - LATEST_TAG=3.7
    - LATEST_TAG=3.6
    - DOCKER_VERSION=17.06.2
  matrix:
#    - TAG=3.7 ALPINE_VER=3.7
    - TAG=3.6 ALPINE_VER=3.6 EXTRA_TAG=3
    - TAG=3.5 ALPINE_VER=3.5
    - TAG=3.4 ALPINE_VER=3.4

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce="${DOCKER_VERSION}~ce-0~ubuntu"

script:
  - travis_retry make && make test

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

    if [[ -n "${TRAVIS_TAG}" ]]; then
      export STABILITY_TAG="${TRAVIS_TAG}"
    fi

    make release

    if [[ -n "${EXTRA_TAG}" ]]; then
      make release TAG="${EXTRA_TAG}"
    fi

    if [[ "${TAG}" == "${LATEST_TAG}" ]]; then
      make release TAG="latest"
    fi
  fi
